version: 2.1

jobs:
  cypress-tests:
    docker:
      - image: cypress/included:15.17.0

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            cd ClickUpCypressApi
            npm install

      - run:
          name: Run Cypress Tests
          command: |
            cd ClickUpCypressApi
            npx cypress run --browser electron

workflows:
  version: 2

  test:
    jobs:
      - cypress-tests
